### ISSUE TITLE
Penerjemahan BNPCHS 2019 - Final

### ISSUE THREAD

**Issue by Berted** [prabowo02/tlx-translations#1]
- [x] A. Bosu Again
- [x] B. 3 Plus 1
- [x] C. Zero Two
- [x] D. Elemen Baru
- [x] E. RBit
- [x] F. Dokemon Orange
- [x] G. Sesi Belajar
- [x] H. Tugas Kelompok
- [x] I. Mencari Tempat Tinggal
- [x] J. Makhluk Kaki Banyak

**Comment by Berted** [comment]
I will translate questions A, C, I

**Comment by tzaph** [comment]
I will translate questions B, D, and F

**Comment by stevennovaryo** [comment]
I take EG

**Comment by VioAlbert** [comment]
ill take H then

**Comment by juancarlovieri** [comment]
I'll take J

**Comment by prabowo02** [comment]
#2 #3 #4 #5 merged

**Comment by prabowo02** [comment]
#6 #7 #8 #12 #14 #16 merged

**Comment by prabowo02** [comment]
All translations available in TLX
