### ISSUE TITLE
Penerjemahan BNPCHS 2018 - Penyisihan

### ISSUE THREAD

**Issue by juancarlovieri** [prabowo02/tlx-translations#10]
- [x] A. Snack
- [x] B. Penjumlahan banyak angka
- [x] C. Lempar dadu
- [x] D. Pergi liburan
- [x] E. Es kepal moli
- [x] F. Tamasya di Bollyjee

**Comment by juancarlovieri** [comment]
I'll take A

**Comment by juancarlovieri** [comment]
I'll take B

**Comment by juancarlovieri** [comment]
I'll take C

**Comment by VioAlbert** [comment]
I'll take E

**Comment by Berted** [comment]
I'll take D

**Comment by prabowo02** [comment]
#18 #19 merged

**Comment by prabowo02** [comment]
#13 #15 #21 merged

**Comment by Berted** [comment]
I'll take F

**Comment by prabowo02** [comment]
#23 merged
