### ISSUE TITLE
Penerjemahan BNPCHS 2018 - Final

### ISSUE THREAD

**Issue by Berted** [prabowo02/tlx-translations#24]
- [x] A. Susu Moli
- [x] B. Blusukan
- [x] C. Amarah sang Dewa
- [x] D. Chairoikoguma
- [x] E. Bermain dengan Bentuk
- [x] F. Super Trombosit
- [x] G. Tikus Atom
- [x] H. World Class Lift
- [x] I. Fingga Boyz
- [x] J. Jelix dan Semut Imut

**Comment by stevennovaryo** [comment]
Lemme take AH

**Comment by juancarlovieri** [comment]
imma take B

**Comment by Berted** [comment]
I'll take C

**Comment by prabowo02** [comment]
#25 #28 #29 merged

**Comment by Berted** [comment]
I'll take F

**Comment by stevennovaryo** [comment]
I'll take the rest

**Comment by prabowo02** [comment]
#30 #31 #33 #35 merged

**Comment by prabowo02** [comment]
#32 #34 #39 merged
