### ISSUE TITLE
Penerjemahan COMPFEST 11 - Penyisihan CPC

### ISSUE THREAD

**Issue by Berted** [prabowo02/tlx-translations#36]
- [x] J - A. Perkalian Chaneka
- [x] J - B. Menggabungkan Monster
- [x] S - A. Belajar Berhitung (J - C)
- [x] S - B. Pak Chanek Sang Dokter Hewan (J - E)
- [x] S - C. Membangun Jalan Aspal
- [x] S - D. Membangun Pos Keamanan
- [x] S - E. Membuat Kelompok
- [x] S - F. Mengubah Karakter
- [x] S - G. Acak Bilangan
- [x] S - H. Penempatan Balon
- [x] S - I. Perlombaan Memasak Kue
- [x] S - J. Pertarungan Terakhir (J - D)

Notes:
J -> Junior
S -> Senior

Keep in mind Junior has subtasks.

**Comment by Berted** [comment]
I'll take S-A and J-A

**Comment by stevennovaryo** [comment]
I'ill take S-G

**Comment by tzaph** [comment]
I'll take J-D and J-E
May take a while, I have to take care of my final exams next week

**Comment by Andrew-Kwok** [comment]
I'll take J-B

**Comment by Andrew-Kwok** [comment]
I'll take S-F

**Comment by Andrew-Kwok** [comment]
I'll take S-E

**Comment by Andrew-Kwok** [comment]
I'll take S-D

**Comment by Andrew-Kwok** [comment]
I'll take S-C

**Comment by Berted** [comment]
I'll take S-H and S-I

**Comment by Berted** [comment]
> I'll take J-D and J-E
> May take a while, I have to take care of my final exams next week

Follow-up, will you be finishing this?

**Comment by Berted** [comment]
> I'll take J-D and J-E
> May take a while, I have to take care of my final exams next week

Follow up, will @tzaph be finishing this?

**Comment by tzaph** [comment]
> > I'll take J-D and J-E
> > May take a while, I have to take care of my final exams next week
> 
> Follow up, will @tzaph be finishing this?

Opened PR for J-D (and S-J), J-E is in progress

**Comment by Andrew-Kwok** [comment]
> I'ill take S-G

I'll take over S-G

**Comment by prabowo02** [comment]
The followings are merged:
#37: Belajar Berhitung
#38: Perkalian Chaneka
#40: Penggabungan Monster
#41: Mengubah Karakter
#42: Membuat Kelompok
#43: Membuat Pos Keamanan
#44: Membangun Jalan Aspal
#45: Perlombaan Memasak Kue
#46: Penempatan Balon
#49: Acak Bilangan

**Comment by prabowo02** [comment]
#50 #51 Pak Chanek Sang Dokter Hewan merged
all problems in the problemset is merged
